[package]
name = "lsb-bitwriter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounded-utils = { path = "../bounded-utils", optional = true }

[lints]
workspace = true
