[package]
name = "hugepage-buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.153"
zerocopy = { version = "0.7.32" }

[lints]
workspace = true
